{% set name = "calmjs.parse" %}
{% set version = "1.2.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 693d18bcfdb14f2a33f64288680adc138275d39de5980fb46f5b882df6e1dbde

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - ply >=3.6
    - python
    - setuptools
  run:
    - ply >=3.6
    - python
    - setuptools

test:
  imports:
    - calmjs
    - calmjs.parse
    - calmjs.parse.handlers
    - calmjs.parse.lexers
    - calmjs.parse.parsers
    - calmjs.parse.testing
    - calmjs.parse.tests
    - calmjs.parse.unparsers

about:
  home: "https://github.com/calmjs/calmjs.parse"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Various parsers for ECMA standards."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
